delivery/catalog/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^products/(?:(?P<name_product>\D+)/)?$', views.product, name="products"),
    re_path(r'^customers/(?:(?P<selected_id>\d+)/)?$', views.cust, name="customers"),
    re_path(r'^subscriptions/(?:(?P<selected_id>\d+)/)?$', views.sub, name="subscriptions"),
    path('orders', views.order, name="orders"),
    re_path(r'^product_detail/(?P<name_product>\D+)/$', views.product_detail, name="product_detail"),
    path('products/prefered', views.prefered_box, name="prefered_box")
    
]

delivery/delivery/urls.py
from django.contrib import admin
from django.urls import path, include


from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(url='catalog/')),
    path('catalog/', include('catalog.urls')),
]

delivery/catalog/models.py
from django.db import models


class Product(models.Model):

    product_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False, blank=False)
    nb_of_meals = models.IntegerField(null=False, blank=False)
    nb_of_persons = models.IntegerField(null=False, blank=False)
    description = models.TextField()

    class Meta:
        db_table = 'product'
    
    def __str__(self):
        return self.name


class Customer(models.Model):

    customer_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255, null=False, blank=False)
    last_name = models.CharField(max_length=255, null=False, blank=False)
    email = models.CharField(max_length=255, null=False, blank=False)
    password = models.CharField(max_length=255, null=False, blank=False)

    class Meta:
        db_table = 'customer'
    
    def __str__(self):
        return self.last_name + " " +self.first_name    


class Subscription(models.Model):

    subscription_id = models.AutoField(primary_key=True)
    status = models.CharField(max_length=85, null=False, blank=False)
    created_at = models.DateTimeField(null=False, blank=True, auto_now_add=True)

    product = models.ForeignKey(Product, models.SET_NULL, null=True, blank=False)
    customer = models.ForeignKey(Customer, models.SET_NULL, null=True, blank=False)

    class Meta:
        db_table = 'subscription'

    def __str__(self):
        return str(self.subscription_id)

    
class Order(models.Model):

    order_id = models.AutoField(primary_key=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=False, blank=False) #ici max = 99,999
    order_date = models.DateTimeField(null=False, blank=True, auto_now_add=True)

    subscription = models.ForeignKey(Subscription, models.SET_NULL, null=True, blank=False)

    class Meta:
        db_table = 'orders'        

    def __str__(self):
        return str(self.order_date)
        

class CounterPrefered(models.Model):

    name = models.CharField(max_length=40, null=False)
    form_date = models.DateTimeField(null=False, blank=True, auto_now_add=True)
    comment = models.TextField()
    counter_classic = models.IntegerField(null=True)
    counter_veggie = models.IntegerField(null=True)
    counter_family = models.IntegerField(null=True)

    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False)

    class Meta:
        db_table = 'counter_prefered'

    def __str__(self):
        return "Vote of " + self.name

delivery/catalog/forms.py
from django import forms
from .models import Product


class PreferedBox(forms.Form):
    """Form class used to collect the name, the prefered box and an eventual comment from a user"""
    name = forms.CharField(max_length=40, label="Enter your name")
    prefered = forms.ModelChoiceField(queryset=Product.objects.all())
    comment = forms.CharField(label="Fill this if you have any comment",required=False)

delivery/catalog/views.py
from django.shortcuts import render

from catalog.models import Product, Customer, Subscription, Order, CounterPrefered
from catalog.forms import PreferedBox


def home(request):
    return render (request, 'catalog/home.html', locals())

def product(request, name_product=None):
    """View rendering the different types of foodboxes and the users rating and comments for each one"""
    products = Product.objects.all()
    #To obtain the number of votes
    counter_classic = CounterPrefered.objects.filter(counter_classic=1).count()
    counter_veggie = CounterPrefered.objects.filter(counter_veggie=1).count()
    counter_family = CounterPrefered.objects.filter(counter_family=1).count()
    counters = CounterPrefered.objects.exclude(comment="").order_by('-form_date')[:3]#We send the 3 last comments
    #We ensure we send an empty list if the comment attribute is set to None    
    votes = []    
    for count in counters:        
        if count.comment:
            votes.append(count)  
    return render(request, 'catalog/product.html', locals())

def cust(request, selected_id=None):
    """View rendering a list of the customers"""
    customers = Customer.objects.order_by('last_name')
    if selected_id:
        selected_id = int(selected_id) #To avoid getting a string in the URL
    return render (request, 'catalog/customer.html', locals())

def sub(request, selected_id=None):
    """View rendering the subscriptions of the customers"""
    subscriptions = Subscription.objects.order_by('-created_at')
    if selected_id:
        selected_id = int(selected_id) #To avoid getting a string in the URL
    return render (request, 'catalog/subscription.html', locals())

def order(request):
    """View rendering the orders done by the customers"""
    orders = Order.objects.order_by('-order_date')
    return render(request, 'catalog/order.html', locals())

def product_detail(request, name_product=None):
    """View rendering the details informations for a given foodbox"""
    product = Product.objects.get(name=name_product)
    return render(request, 'catalog/product_detail.html', {'product': product}) 

def prefered_box(request):
    """View to vote for a favorite box and potentially add a comment"""
    if request.method == 'POST':
        form = PreferedBox(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            prefered = form.cleaned_data['prefered']
            comment = form.cleaned_data['comment']
            sent = True #Allow to change the html to display if the form is valid
                        
            counter = CounterPrefered() #Creation of a CounterPrefered to save the result of the vote
            counter.name = name
            counter.comment = comment

            if prefered.name == "classic":
                counter.counter_classic = 1
                counter.product = Product.objects.get(pk=1)
            elif prefered.name == "veggie":
                counter.counter_veggie = 1
                counter.product = Product.objects.get(pk=2)            
            elif prefered.name == "family":
                counter.counter_family = 1
                counter.product = Product.objects.get(pk=3)
            counter.save()  
    else:
        form = PreferedBox()

    return render(request, 'catalog/prefered.html', locals())



    

delivery/catalog/templates/catalog/customer.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>Customers</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>


    </head>

    <body>

        <div class='container'>
        
            <h1>Customer Page</h1>

            <h2>Find your customers</h2>

            <table class='table table-hover'>

                <thead>
                    <tr>
                        <th>Last name</th>
                        <th>First name</th>                    
                        <th>email adress</th>
                    </tr>
                </thead>

                <tbody>

                    {% for customer in customers %}

                    {% if selected_id == customer.customer_id %}

                        <tr class="highlight">                       

                    {% else %}

                        <tr>
                        
                    {% endif %} 
                    
                            <td>{{ customer.last_name }}</td>
                            <td>{{ customer.first_name }}</td>
                            <td>{{ customer.email }}</td>

                        </tr>                   

                    {% endfor %}

                </tbody>

            </table>

        </div>

    </body>



</html>

delivery/catalog/templates/catalog/home.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>Home</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>

    </head>

    <body>

        <div class='container'>

            <h1>Welcome on the foodboxe website</h1> 

            <div class='container-2'>           

                <h3>On which topic do you want more infos?</h3>

                <div class='row'>  
                
                    <div class='col col-home'><a href="{% url "catalog:orders" %}">All orders</a></div>
                    <div class='col col-home'><a href="{% url "catalog:subscriptions" %}">Subscriptions</a></div>

                </div>

                <div class='row'>

                    <div class='col col-home'><a href="{% url "catalog:customers" %}">Customers</a></div>
                    <div class='col col-home'><a href="{% url "catalog:products" %}">Types of foodboxes</a></div>

                </div>

            </div>
                
        </div>

    </body>

</html>

delivery/catalog/templates/catalog/order.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>Orders</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>

    </head>

    <body>

        <div class='container'>
            
            <h1>List of orders</h1>
            
            <table class='table table-hover'>

                <thead>

                    <tr>
                        <th>Date of ordering</th>
                        <th>Price</th>                        
                        <th>Name of the orderer</th>
                        <th>Type of box</th>
                        <th>Status of the subscription</th>
                    </tr>

                </thead>

                <tbody>                

                    {% for order in orders %}

                        <tr>
                            <td>{{ order.order_date|date:'d/m/Y' }}</td>
                            <td>{{ order.price }}</td>                        
                            <td><a href="{% url "catalog:customers" order.subscription.customer.customer_id %}"><span class="badge badge-primary">
                                {{ order.subscription.customer.first_name }} {{ order.subscription.customer.last_name }}</span></a></td>
                            <td><a href="{% url "catalog:products" order.subscription.product.name %}"><span class="badge badge-success">{{ order.subscription.product.name }}</span></a></td>
                            <td><a href="{% url "catalog:subscriptions" order.subscription.subscription_id %}">{% if order.subscription.status == "ACTIVE" %}<span class="badge badge-info">{% else %}
                                <span class="badge badge-secondary">{% endif %}{{ order.subscription.status }}</span></a></td>
                        </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>

    </body>

</html>

delivery/catalog/templates/catalog/prefered.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>Home</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>

    </head>

    <body>

        </br>

        <div class='container'>

            {% if sent %}Your vote has been sent. Thank you!
            <p><a href="{% url 'catalog:home' %}"><span class="badge badge-success"> Go back to the main menu</a></p>


            {% else %}

            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}    
                <input type="submit" value="Submit" />
            </form>

            {% endif %}
            
        </div>
    
    </body>

</html>

delivery/catalog/templates/catalog/product.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>Products</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>

    </head>

    <body>

        <div class='container'>
        
            <h1>Find the proposed products</h1>

            <table class='table table-hover'>

                <thead>

                    <tr>
                        <th>Name</th>
                        <th>Number of meals</th>
                        <th>Number of persons</th>
                        <th>More infos on the product</th>
                    </tr>

                </thead>

                <tbody>                

                    {% for prod in products %}

                        {% if name_product == prod.name %}

                            <tr class="highlight">                       

                        {% else %}

                            <tr>
                        
                        {% endif %} 

                                <td>{{ prod.name }}</td>
                                <td>{{ prod.nb_of_meals }}</td>
                                <td>{{ prod.nb_of_persons }}</td>
                                <td><a href="{% url 'catalog:product_detail' prod.name %}"> <span class="badge badge-success">
                                    Full description of the {{ prod.name }} box</span></a></td>

                            </tr>
                       
                    {% endfor %}

                </tbody>

            </table> 
            
            <div class="row">

                <div class="col">                      

                    <ul class="list-group">

                        <li li class="list-group-item list-group-item-secondary">Your favorite box:</li>
                        <li class="list-group-item list-group-item-info">{{ counter_classic }} person{{ counter_classic|pluralize }} voted for the classic box </li>
                        <li class="list-group-item list-group-item-success">{{ counter_veggie }} person{{ counter_veggie|pluralize }} voted for the veggie box </li>
                        <li class="list-group-item list-group-item-primary">{{ counter_family }} person{{ counter_family|pluralize }} voted for the family box </li>
                    
                    </ul>

                    </br>

                    <a href = "{% url 'catalog:prefered_box' %}"><span class="badge badge-primary">You want to vote for your favorite box? Click here!</spans></a>

                </div>

                <div class='col'>

                    <ul class='list-group list-group-flush'>

                        <li class = 'list-group-item'><strong>Latest comments about the vote:</strong></li>

                    {% for vote in votes %}

                        <li class = 'list-group-item'>{{ vote.comment }} ---> added the {{ vote.form_date|date:'d/m/Y' }} at {{ vote.form_date|time:'H:i' }} by {{ vote.name }}</li>                                      
                                                            
                    {% empty %}

                        <li class = 'list-group-item'>No comment yet...</li>

                    {% endfor %}

                    </ul>                      
                                                        
                </div>

            </div>

        </div>

    </body>

</html>

delivery/catalog/templates/catalog/product_detail.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>{{ product.name }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>

    </head>

    <body>

        <div class="container cont-details">
        
            <h1>The {{ product.name }} box</h1>
        
            <p>This box is for <strong> {{ product.nb_of_persons }} persons</strong>, and it will cover <strong>{{ product.nb_of_meals }} meals</strong></p>
            <p><em>{{ product.description }}</em></p>
        
        </div>

    </body>

</html>

delivery/catalog/templates/catalog/subscription.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>Subscription</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>

    </head>

    <body>

        <div class='container'>
        
            <h1>Subscriptions</h1>

            <table class='table table-hover'>

                <thead>

                    <tr>
                        <th>Id</th>
                        <th>Status</th>
                        <th>Date of creation</th>
                        <th>Related product</th>
                        <th>Related customer</th>
                    </tr>

                </thead>

                <tbody>

                    {% for sub in subscriptions %}

                        {% if selected_id == sub.subscription_id %}

                            <tr class="highlight">                       

                        {% else %}

                            <tr>
                        
                        {% endif %}                        
                        
                                <td>{{ sub.subscription_id  }}</td>
                                <td>{% if sub.status == "ACTIVE" %}<span class="badge badge-info">{% else %}
                                    <span class="badge badge-secondary">{% endif %}{{ sub.status }}</span></td>
                                <td>{{ sub.created_at }}</td>
                                <td><a href="{% url "catalog:products" sub.product.name %}"><span class="badge badge-primary">{{ sub.product.name }}</span></a></td>
                                <td><a href="{% url "catalog:customers" sub.customer.customer_id %}">
                                    <span class="badge badge-success">{{ sub.customer.first_name }} {{sub.customer.last_name}}</span></td>
                            
                            </tr>

                    {% endfor %}

                </tbody>

            </table>
            
        </div>

    </body>

</html>